import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import NavBarWrapper from "@/components/navbar/NavBarWrapper";
import { StoreProviders } from "@/redux/StoreProviders";
import { ErrorBoundary } from "next/dist/client/components/error-boundary";
import Error from "./error";

const quicksand = Quicksand({
  variable: "--font-quicksand",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "eCommerce Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          rel="stylesheet"
          href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/7.0.0/css/all.min.css"
        />
      </head>
      <body
        className={`${quicksand.className} ${quicksand.className} antialiased`}
      >
        <StoreProviders>
          <ErrorBoundary errorComponent={Error}>
            <NavBarWrapper />
            {children}
          </ErrorBoundary>
        </StoreProviders>
      </body>
    </html>
  );
}
